### ISSUE TITLE
Mejoras

### ISSUE THREAD

**Issue by ytaylordev** [Adalab/modulo-1-evaluacion-intermedia-SaraRivAl#1]
Muy buen trabajo @SaraRivAl!!!

Aquí tienes unos consejos para mejorar tu ejercicio:

- [x] CARPETAS > CSS: La ruta del fichero CSS debe empezar por `./styles/` o `./css/`.
- [x] CARPETAS > IMG: Los ficheros de imágenes deben empezar por `./images/` o `./img/`.
- [x] Esto no es una buena practica, agrega los estilos a los ficheros de estilos: https://github.com/Adalab/modulo-1-evaluacion-intermedia-SaraRivAl/blob/398139cc7fde4312c03dc9cc1b003013a9796771/index.html#L15-L27 
- [x] HTML > HEADER: La etiqueta `img` debe tener el atributo `title`.
- [x] HTML > HEADER: El texto del primer enlace debe ser "Blog". Debemos ponerlo en mayúsculas con CSS.
- [x] HTML > HEADER: El texto del primer enlace debe ser "Contacto". Debemos ponerlo en mayúsculas con CSS.
- [x] HTML > HEADER: Los enlaces tienen que tener el atributo `title`.
- [x] HTML > MAIN: El contenido exacto del h1 debe ser "Creando diversidad digital". Debemos poner las primeras letras en mayúsculas con CSS.
- [x] No abuses del uso de la etiqueta <br>: https://github.com/Adalab/modulo-1-evaluacion-intermedia-SaraRivAl/blob/398139cc7fde4312c03dc9cc1b003013a9796771/index.html#L45 
- [x] CSS > ESTILOS REPETIDOS: Hay estilos repetidos en las media queries que no son necesarios, es mejor quitarlos.
- [x] CSS > FONT-FAMILY: Es recomendable que la fuente del body sea Rubik para aprovechar la herencia.
- [x] CSS > FONT-SIZE: El tamaño del h1 en tablet debe ser 40px.
- [x] CSS > PADDING: El padding de los enlaces no debería ser 0. Auméntalo para aumentar el área clickable, pero manteniendo los requisitos del diseño.
- [x] CSS > FIXED: La cabecera debe medir todo el ancho de la página. Utiliza una medida u otra: https://github.com/Adalab/modulo-1-evaluacion-intermedia-SaraRivAl/blob/398139cc7fde4312c03dc9cc1b003013a9796771/STYLES/style.css#L13 
- [x] CSS > FLEX: El HEADER en tablet debe tener los elementos alineados a izquierda y derecha .

Es posible que cuando corrijas uno de estos puntos, otros se corrijan solos, ya que unos dependen de otros.

Y recuerda algo muy importante:

- Escribe tu código en inglés.
- Escribe todos los ficheros y carpetas en inglés.
- Los commits también tienen que ser en inglés, empezando por un verbo en infinitivo.

Ánimo y si tienes cualquier duda avísame!!!

> Con cada mejora que hagas, márcala como completada en este issue y su súbela a este repo.

> Este issue ha sido creado automáticamente por ello puede tener algún error, si hay algo que no te encaja escribe por slack al coordinador de Adalab.

> Para corregir el ejercicio buscamos determinadas palabras en el código para identificar las secciones. Por ejemplo buscamos **Creando** para buscar el título de la página. Si has escrito mal alguna palabra en el código es posible que te aparezcan aquí falsos errores.

> Por favor no cierres este issue, ya lo haremos nosotros.

**Comment by SaraRivAl** [comment]
Hola Yanelis,
Muchas gracias por tus indicaciones. Creo que ya está todo lo que me has dicho corregido.
Disculpa que solo haga un commit con todo. Voy un poco apurada y no leí correctamente ese punto. Me pongo como tarea mejorar también en la atención a las instrucciones.
Un abrazo
